# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8],[7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

In [5]:
# Multi-dimensional (Matrix definition) 
my_matrix1 = np.array([[3, 7, 9, 3],[4, 3, 2, 2]])
my_matrix1

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [6]:
my_mini1 = np.array([[3, 7, 9, 3],[4, 3, 2, 2]])
my_mini1

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.18304288, 0.90306179, 0.86858397, 0.09396702, 0.57277824,
       0.49981979, 0.09740155, 0.71491381, 0.55943323, 0.39617512,
       0.76963149, 0.1862    , 0.35136216, 0.79286795, 0.06226824,
       0.05610442, 0.4894347 , 0.88371911, 0.43488784, 0.66258467])

In [12]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.39628272, 0.72036169, 0.13146449],
       [0.6293951 , 0.05357426, 0.74747782],
       [0.49687146, 0.91083508, 0.82288273]])

In [9]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

21

In [10]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([75, 22, 36, 48, 74, 47, 93,  2, 86, 28, 24, 12, 62, 94, 92],
      dtype=int32)

In [11]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 51)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
# Matrix of ones
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
user_num = int(input("Enter a random number"))



In [15]:
x = np.random.randint(1, user_num, 10)
x

array([11,  1,  4,  2, 11,  5, 10,  6,  1, 10], dtype=int32)

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [16]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y = np.arange (1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
sq_root = np.sqrt(squared)
sq_root

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
expon_z = np.exp(y)
expon_z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [40]:
x = np.array([5,7,20])
y = np.array([9,15,4])
dist = np.sqrt(x**2 + y**2)
dist

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [41]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [43]:
# Access specific index from the numpy array
my_numpy_array[-1]

50

In [45]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3] #Start from index 0 and not inlcude 3

array([3, 5, 6])

In [47]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [48]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[7, 5, 3, 4],
       [5, 3, 1, 7],
       [5, 6, 9, 6],
       [3, 5, 8, 4]])

In [49]:
# Get a row from a mtrix
matrix[0]

array([7, 5, 3, 4])

In [51]:
# Get one element
matrix[0][2]

3

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [54]:
X = np.array([ [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [55]:
X[4]=0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [56]:
matrxi = np.random.randint(1,10,(5,5))
matrxi

array([[5, 9, 6, 7, 8],
       [5, 6, 9, 5, 4],
       [1, 6, 6, 4, 2],
       [8, 1, 1, 2, 6],
       [5, 9, 3, 5, 4]])

In [57]:
new_mat = matrxi[matrxi > 7]
new_mat

array([9, 8, 9, 8, 9])

In [62]:
# Obtain odd elements only
new_mat1 = matrxi[matrxi % 2 != 0]
print(new_mat1)
new_mat2 = matrxi[matrxi % 2 == 0]
new_mat2

[5 9 7 5 9 5 1 1 1 5 9 3 5]


array([6, 8, 6, 4, 6, 6, 4, 2, 8, 2, 6, 4])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [63]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [64]:
X[X<0]=0
X[X%2!=0]=-2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [1]:
import pandas as pd

In [2]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth $':[3500,29000,10000,2000],
                              'Years with bank':[3,4,5,6]})

bank_client_df

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                5
3             444             Ryan         2000                6

In [3]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [4]:
# you can only view the first couple of rows using .head()
bank_client_df.head()

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                5
3             444             Ryan         2000                6

In [5]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail()

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                5
3             444             Ryan         2000                6

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [6]:
portfolio_df = pd.DataFrame({ 'ticker Symbol':['AAPL','AMZN','T','GOOG'],
                              'number of shares':[3,3,3,3],
                              'Price per share':[100,200,300,400]})

portfolio_df

ticker Symbol  number of shares  Price per share
0          AAPL                 3              100
1          AMZN                 3              200
2             T                 3              300
3          GOOG                 3              400

In [7]:
stock_value = portfolio_df['Price per share'] * portfolio_df['number of shares']
stock_value.sum()

3000

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [9]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [10]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [21]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [11]:
ret_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
ret_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [16]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth $':[3500,29000,10000,2000],
                              'Years with bank':[3,4,5,6]})

bank_client_df

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                5
3             444             Ryan         2000                6

In [17]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank']>=5]
df_loyal

Bank Client ID Bank Client Name  Net Worth $  Years with bank
2             333            Mitch        10000                5
3             444             Ryan         2000                6

In [18]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth $  Years with bank
0           Chanel         3500                3
1            Steve        29000                4
2            Mitch        10000                5
3             Ryan         2000                6

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [20]:
df_networth = bank_client_df[bank_client_df['Net Worth $']>=5000]
df_networth

Bank Client Name  Net Worth $  Years with bank
1            Steve        29000                4
2            Mitch        10000                5

In [21]:
df_networth['Net Worth $'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [8]:
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [9]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [10]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)


0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [11]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [12]:
def networth_update(balance):
    return balance * 3 + 200

In [13]:
results = bank_client_df['Net worth [$]'].apply(networth_update)

In [14]:
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [15]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [16]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [17]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [18]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True)

In [19]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [22]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']},
                  index = [0,1,2,3])

In [23]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [24]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [25]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [26]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                   'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],
                   'D':['D8','D9','D10','D11']},
                  index = [4,5,6,7])

In [27]:
df3

A    B    C    D
4   A8   B8   C8   D8
5   A9   B9   C9   D9
6  A10  B10  C10  D10
7  A11  B11  C11  D11

In [28]:
pd.concat([df1,df2,df3])

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
4   A4   B4   C4   D4
5   A5   B5   C5   D5
6   A6   B6   C6   D6
7   A7   B7   C7   D7
4   A8   B8   C8   D8
5   A9   B9   C9   D9
6  A10  B10  C10  D10
7  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [29]:
raw_data = {'Bank Client ID':['1','2','3','4','5'],
           'First Name':['Nancy','Alex','Shep','Max','Alan'],
           'Last Name':['Rob','Ali','George','Mitch','Steve']}

In [31]:
Bank_df1 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])
Bank_df1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5       Alan     Steve

In [32]:
raw_data = {'Bank Client ID':['6','7','8','9','10'],
           'First Name':['Bill','Diana','Sarah','Heather','Holly'],
           'Last Name':['Chris','Mo','GIll','Rob','Lopez']}
Bank_df2 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])
Bank_df2

Bank Client ID First Name Last Name
0              6       Bill     Chris
1              7      Diana        Mo
2              8      Sarah      GIll
3              9    Heather       Rob
4             10      Holly     Lopez

In [34]:
raw_data = {'Bank Client ID':['1','2','3','4','5','6','7','8','9','10'],
           'Annual Salary':[25000,35000,45000,48000,50000,52000,60000,72000,82000,100000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary'])
bank_df_salary

Bank Client ID  Annual Salary
0              1          25000
1              2          35000
2              3          45000
3              4          48000
4              5          50000
5              6          52000
6              7          60000
7              8          72000
8              9          82000
9             10         100000

In [36]:
bank_df_all = pd.concat([Bank_df1, Bank_df2])
bank_df_all

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5       Alan     Steve
0              6       Bill     Chris
1              7      Diana        Mo
2              8      Sarah      GIll
3              9    Heather       Rob
4             10      Holly     Lopez

In [37]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name Last Name  Annual Salary
0              1      Nancy       Rob          25000
1              2       Alex       Ali          35000
2              3       Shep    George          45000
3              4        Max     Mitch          48000
4              5       Alan     Steve          50000
5              6       Bill     Chris          52000
6              7      Diana        Mo          60000
7              8      Sarah      GIll          72000
8              9    Heather       Rob          82000
9             10      Holly     Lopez         100000

In [38]:
new_client = {'Bank Client ID':['11'],
             'First Name':['Ryana'],
             'Last Name':['Pete'],
             'Annual Salary': [89000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID','First Name','Last Name','Annual Salary'])

In [39]:
new_client_df

Bank Client ID First Name Last Name  Annual Salary
0             11      Ryana      Pete          89000

In [40]:
new_df = pd.concat ([bank_df_all,new_client_df], axis = 0)
new_df

Bank Client ID First Name Last Name  Annual Salary
0              1      Nancy       Rob          25000
1              2       Alex       Ali          35000
2              3       Shep    George          45000
3              4        Max     Mitch          48000
4              5       Alan     Steve          50000
5              6       Bill     Chris          52000
6              7      Diana        Mo          60000
7              8      Sarah      GIll          72000
8              9    Heather       Rob          82000
9             10      Holly     Lopez         100000
0             11      Ryana      Pete          89000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df